name: Daily donate in 12306

on:
  push:
    branches:
      - master
  workflow_dispatch: 
  schedule:
    - cron: '0 30 16 ? * 7'

jobs:
  dy_auto_donate_helper:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: pip install -r requirements.txt
      - name: 'Set driver'
        run: sudo chmod -R 777 ./chrome/chromedriver
      - name: 'Working'
        env:
#          ACF_AUTH: ${{ secrets.ACF_AUTH }}
#          ACF_UID: ${{ secrets.ACF_ACF_UID }}
#          ACF_USERNAME: ${{ secrets.ACF_USERNAME }}
#          ACF_NICKNAME: ${{ secrets.ACF_NICKNAME }}
#          DY_AUTH: ${{ secrets.DY_AUTH }}
          SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
          COOKIES: ${{ secrets.COOKIES }}
        run: |
          sudo cp -p ./chrome/chromedriver /usr/bin/
          chmod -R 777 /usr/bin/chromedriver
          python main.py
